# Use root/example as user/password credentials

version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - /data/redis:/data  # 将 Redis 数据存储到项目目录下的 data 文件夹
    command: redis-server --requirepass my-secret-pw  # 设置 Redis 密码
